### ISSUE TITLE
Prototype Town bugs

### ISSUE THREAD

**Issue by seanlazaro** [seanlazaro/JRPG#3]
1. Player can walk on top of trees and roofs
2. Get rid of the cactus in the forest clearing
3. There should be a bit of land that allows the player to walk around the lake
4. There's a half-tree beside the library
5. There should be some mushrooms in town
6. Make collision boxes of stumps, bushes and piles of wood smaller (more similar to the actual shape of the game object)
7. When the player tries to exit the town, this should start a dialogue where the player is the speaker and says to himself that he shouldn't leave until his mission is finished
8. There are no collision boxes in the table and chairs at the top right part of the first floor of the inn
9. There are invisible collision boxes in the central hallway of the library

**Comment by shaunlazaro** [comment]
Fixed EVERYTHING

**Comment by seanlazaro** [comment]
There are flowers at the edge of the lake path that float on top of the player's body

**Comment by shaunlazaro** [comment]
Fixed, and this type of fix shouldn't need review
